name: neuralbabytalk
channels:
  - PyTorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2018.8.24=py35_1
  - cffi=1.11.5=py35he75722e_1
  - cudatoolkit=10.0.130=0
  - cython=0.28.5=py35hf484d3e_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.3=199
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py35h7dd41cf_0
  - mkl_random=1.0.1=py35h4414c95_1
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py35h6bb024c_1
  - numpy=1.15.2=py35h1d66e8a_0
  - numpy-base=1.15.2=py35h81de0dd_0
  - olefile=0.46=py35_0
  - openssl=1.0.2r=h7b6447c_0
  - pillow=5.2.0=py35heded4f4_0
  - pip=10.0.1=py35_0
  - pycparser=2.19=py35_0
  - python=3.5.6=hc3d631a_0
  - pytorch=1.0.1=py3.5_cuda10.0.130_cudnn7.4.2_2
  - readline=7.0=h7b6447c_5
  - setuptools=40.2.0=py35_0
  - six=1.11.0=py35_1
  - sqlite=3.27.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.1=py35_0
  - wheel=0.31.1=py35_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - cycler==0.10.0
    - kiwisolver==1.0.1
    - matplotlib==3.0.3
    - pycocotools==2.0.0
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
prefix: /home/dexter/miniconda3/envs/advanced_ml

